site_name: dataZ Documentation
repo_url: https://github.com/dataz/dataz-doc
pages:
- Home: 'index.md'
- Install : 'install.md'
- Tutorials :
    - Getting Started : 'tutorials/getting-started.md'
- About:
    - 'License': 'about/license.md'
    - 'Release Notes': 'about/release-notes.md'
theme: readthedocs
